version: "3"
services:
    jenkins-master:
        image: jenkins_dood:v1
        ports:
            - 8090:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_data:/var/jenkins_home
volumes:
    jenkins_data:
