version: "3"
services:
    jenkins-master:
        image: jenkinsci/blueocean
        ports:
            - 8090:8080
            - 50000:50000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_data:/var/jenkins_home
        privileged: true
volumes:
    jenkins_data:
