version: "3"
services:
    jenkins-master:
        image: jenkins_dood:v2
        restart: always
        ports:
            - 8090:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_data:/var/jenkins_home
            - $(which docker):/bin/docker
volumes:
    jenkins_data:
