version: '3'
services:
  portainer-master:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 8091:9000
    networks:
      - portainer-network

networks:
  portainer-network:
    external: true

volumes: 
  - portainer_data